export const MOVIES = [
  {
    id: "1",
    title: "Final Champions League 2026",
    description: "Acompanhe todos os lances da grande final europeia em tempo real.",
    thumbnailUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=1200",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    duration: "2h 30m",
    category: "Lançamentos",
    genre: "Esporte",
    rating: "98%",
    year: 2026,
  },
  {
    id: "2",
    title: "NBA Finals: Game 7",
    description: "A decisão máxima do basquete mundial direto de Phoenix.",
    thumbnailUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?q=80&w=1200",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    duration: "1h 45m",
    category: "Lançamentos",
    genre: "Basquete",
    rating: "95%",
    year: 2026,
  },
  {
    id: "3",
    title: "SFL Sports: 24h Ao Vivo",
    description: "Sua dose diária de notícias, análises e jogos em tempo real.",
    thumbnailUrl: "https://images.unsplash.com/photo-1504450758481-7338eba7524a?q=80&w=1200",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    duration: "Ao Vivo",
    category: "Canais ao Vivo",
    genre: "Live",
    rating: "100%",
    year: 2026,
  },
  {
    id: "4",
    title: "Arena SFL",
    description: "Debates e polêmicas com os melhores comentaristas do Brasil.",
    thumbnailUrl: "https://images.unsplash.com/photo-1595435063435-0c58e57999dc?q=80&w=1200",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    duration: "1h 15m",
    category: "Canais ao Vivo",
    genre: "Talk Show",
    rating: "89%",
    year: 2026,
  },
  {
    id: "5",
    title: "Império do Futebol",
    description: "A série documental que revela os segredos dos grandes clubes.",
    thumbnailUrl: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?q=80&w=1200",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    duration: "10 Eps",
    category: "Séries Premium",
    genre: "Documentário",
    rating: "97%",
    year: 2025,
  },
  {
    id: "6",
    title: "Lendas das Pistas",
    description: "A vida e carreira dos pilotos que marcaram a era de ouro da F1.",
    thumbnailUrl: "https://images.unsplash.com/photo-1547447134-cd3f5c716030?q=80&w=1200",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    duration: "8 Eps",
    category: "Séries Premium",
    genre: "Esporte",
    rating: "99%",
    year: 2025,
  },
];
